#JPA config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunwu
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  #Session存储类型
  session:
    store-type: hash_map

logging:
  level: debug
security:
  basic:
    enabled: false

#关闭Http验证